### ISSUE TITLE
Unexpected token in MathUtil.js

### ISSUE THREAD

**Issue by jelmervdl** [terrestris/base-util#15]
Hi,

When trying to include the react-geo module, the build breaks on an unexpected token in MathUtil.js. The static variables are not being accepted. When I convert them to true static methods, they compile as expected.

Node v10.8.0, after creating a react app via `yarn create react-app my-app`.

(The same happens in MapUtil.js of the ol-util module by the way. I can create pull requests for both if appreciated 😄 )

**Comment by marcjansen** [comment]
AFAICT this is because we publish ES6 modules on npm which aren't understood by CRA. Ping @kaivolland, correct? Can we publish ES5 additionally? Can you link to your remarks wrt ejecting etc.? TIA

**Comment by marcjansen** [comment]
I think this is related: https://github.com/terrestris/react-geo/issues/851#issuecomment-418040107

**Comment by marcjansen** [comment]
@jelmervdl If there is something we can do on our side to make this usable for e.g. CRA and still publish valid ES6, I'd say PRs very much welcome. A notice on the readme might also help in the meantime. Thanks in advance.

**Comment by KaiVolland** [comment]
We might shoukld switch to ES5. Seems to cause a lot of problems.

**Comment by annarieger** [comment]
A possible solution to avoid transpiling error in CRA based projects is to force including of affected dependencies to be used with `babel-loader` in `webpack` config file like
```javascript
{
    test: /\.(js|jsx|mjs)$/,
    include: [
        paths.appSrc,    
        path.resolve(paths.appNodeModules, '@terrestris/base-util'),
        path.resolve(paths.appNodeModules, '@terrestris/ol-util')
        [...]
    ],
    loader: require.resolve('babel-loader'),
    options: {...},
},
```

s. also https://github.com/facebook/create-react-app/issues/1125#issuecomment-267920849

This fixed the failing build of CRA app in some another project for me.

**Comment by dnlkoch** [comment]
As of version 0.1.2 we publish both `ES5` and `ES6` modules so this issues should be resolved.
